# Generated by Django 6.0.3 on 2026-03-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('no_of_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('experience', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, upload_to='teachers/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.department')),
            ],
        ),
    ]
