# Generated by Django 6.0.3 on 2026-03-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='department.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
