# Generated by Django 6.0.3 on 2026-03-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_department_id'),
        ('teacher', '0002_alter_teacher_department_alter_teacher_teacher_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_image',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
