# Generated by Django 6.0.3 on 2026-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_scheduleproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(max_length=50, verbose_name='Class (e.g. S5 - IDAI)'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_name',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher_name',
            field=models.CharField(max_length=100, verbose_name='Teacher Name'),
        ),
    ]
