# Generated by Django 6.0.3 on 2026-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du jour férié')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('holiday_type', models.CharField(choices=[('national', 'Jour Férié National'), ('religious', 'Fête Religieuse'), ('school', 'Vacances Scolaires'), ('other', 'Autre')], default='national', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jour Férié',
                'verbose_name_plural': 'Jours Fériés',
                'ordering': ['start_date'],
            },
        ),
    ]
