# Generated by Django 6.0.3 on 2026-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('no_of_students', models.IntegerField(default=0)),
            ],
        ),
    ]
